#!/usr/bin/env bash

#DIR="$HOME/.dotfiles/hypr/.config/hypr/assets/backgrounds"
DIR="$HOME/Downloads/wallpapers"

# a simple wallpaper picker
awww img $(find $DIR -type f | vicinae dmenu --no-metadata -p 'Pick a wallpaper...') --transition-type=any
