set-option -g default-terminal "screen-256color"
set -s escape-time 0

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'vaaleyard/tmux-dotbar'
# Enable bell detection in tmux
set -g monitor-bell on
set -g bell-action any

# Show bell icon in tmux-dotbar window titles
set -g @tmux-dotbar-window-status-format '#{?window_bell_flag,󰂚 ,} #W '
set -g @tmux-dotbar-right "true"
set -g @tmux-dotbar-status-right-text " %H:%M "
set -g @tmux-dotbar-rounded "true"
set -g @tmux-dotbar-session-text "[#S]"
set -g status-left-length 50

set -g mouse on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set-hook -g after-new-session "source-file ~/.tmux.conf"

# Reload config
bind r source-file ~/.tmux.conf
set -g base-index 1

# colors
#set -g status-style 'bg=#282828 fg=#5eacd3'

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/.dotfiles/personal/todo.md"

# tmux-sessionzer
bind l display-popup -E "tmux neww tmux-sessioniser"

run '~/.tmux/plugins/tpm/tpm'
